conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logoutApi, name='logoutApi'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('catapi/',views.CategoryView.as_view(), name='catapi'),
    path('itemapi/',views.ItemView.as_view(),name='itemapi'),
    path('is_auth/',views.is_auth,name='is_auth')
]
 

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontend.urls')),
    path('core/', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item
from .forms import SignupForm
from django.contrib.auth import logout

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def about(request):
    return render(request, 'core/about.html')


def logoutApi(request):
    logout(request)
    return redirect('/core/login')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/core/login')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}Title{% endblock %}

{% block content %}
<div style="margin-top: 75px; margin-right: 40px; margin-left: 40px">
  <h2 class="font-bold">About ReactJS</h2>
  <p>
    A well-liked JavaScript library for creating user interfaces, especially for
    single-page apps, is called ReactJS. React is a Facebook project that uses a
    component-based architecture to make the process of developing interactive
    user interfaces easier. Reusable components can be combined to create
    intricate user interfaces.The virtual DOM (Document Object Model), one of
    React's primary features, enhances efficiency by reducing the number of
    updates to the real DOM. React speeds up rendering by comparing the virtual
    and actual DOMs when a component's state changes and only updating the
    relevant elements.Additionally, React encourages declarative programming, in
    which programmers define the UI's appearance based on the state of the
    application, as opposed to forcing changes to the DOM. his makes the code
    more predictable and easier to understand. React's ecosystem includes tools
    like React Router for managing routes, Redux for managing application state,
    and React Native for building native mobile applications. It also has a
    large and active community, with a wealth of third-party libraries and
    resources available to help developers build powerful and efficient web
    applications.
  </p>
  <h2 class="font-bold">About Django</h2>
  <p>
    Django is a powerful and high-level open-source web framework written in
    Python. It was created with the aim of simplifying and accelerating the
    development of web applications. Django follows the "batteries-included"
    philosophy, which means it provides a wide array of built-in features and
    tools to make web development easier and more efficient. One of Django's
    standout features is its robust and secure authentication system, which
    allows developers to handle user authentication and authorization
    effortlessly. It also includes an Object-Relational Mapping (ORM) system
    that abstracts database interactions, enabling developers to work with
    databases using Python classes and objects, rather than writing SQL queries
    directly. Django follows the Model-View-Controller (MVC) architectural
    pattern, or more precisely, the Model-View-Template (MVT) pattern. This
    separation of concerns makes it easier to maintain and scale applications.
    Additionally, Django's templating engine simplifies the creation of dynamic
    and reusable HTML templates. Django's ecosystem is rich with reusable
    components and packages known as "Django apps" that can be integrated into
    projects. It also has an active and supportive community, making it easy to
    find documentation, tutorials, and assistance. With Django, developers can
    rapidly build secure, scalable, and feature-rich web applications, making it
    an ideal choice for startups, enterprises, and individual developers alike.
    Its versatility, strong community support, and emphasis on best practices
    have made it a preferred framework for web development.
  </p>
</div>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="icon"
      type="image/x-icon"
      href="../../../media/item_images/public-service.png"
    />

    <title>{% block title %}{% endblock %} | Service Sage</title>
  </head>

  <body>
    <nav
      class="py-6 px-6 flex justify-between items-center border-b border-black-200"
    >
      <a href="/" class="text-xl font-semibold">Service Sage</a>

      <div class="space-x-6">
        <!-- <a href="{% url 'item:new' %}" class="px-6 py-3 text-lg font-semibold bg-cyan-500 hover:text-gray-500">New item</a>
                <a href="{% url 'item:items' %}" class="px-6 py-3 text-lg font-semibold bg-cyan-500 hover:text-gray-500">Browse</a> -->

        {% if request.user.is_authenticated %}
        <a
          href="{% url 'item:new' %}"
          class="text-lg font-semibold hover:text-gray-500"
          >New item</a
        >
        <a
          href="{% url 'item:items' %}"
          class="text-lg font-semibold hover:text-gray-500"
          >Browse</a
        >
        <a
          href="{% url 'conversation:inbox' %}"
          class="px-6 py-3 text-lg font-semibold bg-cyan-500 text-black hover:bg-teal-700"
          >Inbox</a
        >
        <a
          href="{% url 'dashboard:index' %}"
          class="px-6 py-3 text-lg font-semibold bg-cyan-500 bg-cyan-500 text-black hover:bg-gray-700"
          >Dashboard</a
        >
        <a
          href="{% url 'core:logoutApi' %}"
          class="px-6 py-3 text-lg font-semibold bg-cyan-500 bg-cyan-500 text-black hover:bg-gray-700"
          >Logout</a
        >
        {% else %}
        <a
          href="{% url 'core:signup' %}"
          class="px-6 py-3 text-lg font-semibold bg-cyan-500 text-purple hover:bg-teal-700"
          >Sign up</a
        >
        <a
          href="{% url 'core:login' %}"
          class="px-6 py-3 text-lg font-semibold bg-cyan-500 text-purple hover:bg-gray-700"
          >Log in</a
        >
        {% endif %}
      </div>
    </nav>

    <div class="px-6 py-6">{% block content %} {% endblock %}</div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
      <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">About</h3>

        <p class="text-lg text-gray-500">
          This project represents the culmination of our final year, where we
          developed a dynamic web application using Django and ReactJS. It's
          primary goal is to develop a E-marketplace website, where customer can
          access wide range of product and services.
        </p>
        <a
          href="https://www.flaticon.com/free-icons/customer-service"
          title="customer service icons"
        >
          Customer service icons created by Awicon - Flaticon
        </a>
      </div>

      <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

        <ul class="space-y-2">
          <li>
            <a
              href="{% url 'core:about' %}"
              class="text-lg text-teal-500 hover:text-teal-700"
              >About</a
            >
          </li>
          <li>
            <a
              href="{% url 'core:contact' %}"
              class="text-lg text-teal-500 hover:text-teal-700"
              >Contact</a
            >
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<div class="container" style="margin-top: 75px;">
    <h1 class="text-center">Contact Us</h1>
    <p class="text-center">We'd love to hear from you:</p>
    
    <div class="contact-details">
      <h2><b><u>Our Contact Details</u> :-</b></h2>
      <p><strong>Name:</strong>Pushpam Priya</p>
      <p><strong>Email:</strong> pushpam.priyaa@iilmcet.ac.in</p>
    </div>
    <div class="contact-details">
      <h2>-----------------------------------------------------------------------</h2>
      <p><strong>Name:</strong>Hari Om Gupta</p>
      <p><strong>Email:</strong>hariom.gupta.cs24@iilmcet.ac.in</p>
      <!-- <p><strong>Skills</strong> Python, Django, MySql, ReactJS </p> -->
    </div>
    <div class="contact-details">
      <h2>-----------------------------------------------------------------------</h2>
      <p><strong>Name:</strong>Anjali Choudhary</p>
      <p><strong>Email:</strong> anjali.choudhary.cs24@iilmcet.ac.in</p>
      <!-- <p><strong>Skills</strong> Python, Django, MySql, ReactJS </p> -->
    </div>
    <div class="contact-details">
      <h2>-----------------------------------------------------------------------</h2>
      <p><strong>Name:</strong>Manmohan Gupta</p>
      <p><strong>Email:</strong>manmohan.gupta.cs24@iilmcet.ac.in</p>
      <!-- <p><strong>Skills</strong> Python, Django, MySql, ReactJS </p> -->
    </div>
  </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 flex items-center justify-center">Log In</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 flex flex-col items-center">Submit</button>
    </form>
</div>
{% endblock %}